function sendEmailTicketRequest() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet();
  const emailSheet = sheet.getSheetByName("emails_list");
  const lastTicketSheet = sheet.getSheetByName("last_ticket");

  // Links
  const ticket_link = "https://docs.google.com/spreadsheets/d/1ucFGWJT6NjXG0VFG2anscS8RPELydIrxr4Kxrax-dGs/edit?gid=0#gid=0";
  // const chat_link = "https://chat.google.com/room/AAQAs-g2H4k?cls=7"; // old
  const chat_link = "https://chat.google.com/room/AAQAexhKSzQ?cls=7;"


  // --- Get email addresses and clean them ---
  const toEmails = (emailSheet.getRange("A1").getValue() || "").toString().trim();
  const ccEmails = (emailSheet.getRange("B1").getValue() || "").toString().trim();

  // --- Get required fields ---
  const description = lastTicketSheet.getRange("F1").getValue();
  const ticketId = lastTicketSheet.getRange("G1").getValue();
  const requestType = lastTicketSheet.getRange("D1").getValue();
  const requestPriority = lastTicketSheet.getRange("E1").getValue();

  // --- Get timestamp (confirm correct cell) ---
  const timestampCell = lastTicketSheet.getRange("A1").getValue(); // change cell if needed

  // Validate timestamp
  if (!timestampCell) {
    Logger.log("No timestamp found, email not sent.");
    return;
  }

  const currentTimestamp = (timestampCell instanceof Date)
    ? Utilities.formatDate(timestampCell, Session.getScriptTimeZone(), "MM-dd-yyyy HH:mm:ss")
    : timestampCell.toString();

  // --- Use separate key for ticket email ---
  const scriptProps = PropertiesService.getScriptProperties();
  const lastTimestamp = scriptProps.getProperty("lastSentTicketTimestamp");

  // --- Send only if new ---
  if (currentTimestamp && currentTimestamp !== lastTimestamp) {
    // Validate required fields
    if (!ticketId || !requestType || !requestPriority) {
      Logger.log("Missing required fields for ticket email, not sent.");
      return;
    }

    const subject = `[${requestPriority}] ${ticketId} - IT Ticket Request: ${requestType}`;

    const body = `
      <p><strong>New IT Ticket Request:</strong></p>
      <p>Request Type: ${requestType}<br>
        Request Priority: ${requestPriority}<br>
        Description: ${description}</p>
      <p><a href="${ticket_link}">Click here to view the status</a></p>
      <p><a href="${chat_link}">You can chat with IT Team Here</a></p>
      <p>This email is generated by BI Team<br>
        Best Regard,<br>
      <strong>Marathon BI Team</strong></p>
    `;

    try {
      MailApp.sendEmail({
        to: toEmails,
        cc: ccEmails,
        subject: subject,
        htmlBody: body,
        name: 'Marathon BI'
      });
      Logger.log("M Tech - Ticket Request confirmation email sent: " + ticketId + "!");

      // Save timestamp
      scriptProps.setProperty("lastSentTicketTimestamp", currentTimestamp);
    } catch (e) {
      Logger.log("!Error sending ticket email: " + e.toString());
    }
  } else {
    Logger.log("No new ticket timestamp or timestamp already processed!");
  }
}


function sendEmailNewProject() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet();
  const emailSheet = sheet.getSheetByName("emails_list");
  const lastNewProject = sheet.getSheetByName("last_new_project");

  // Links
  const new_project_link = "https://docs.google.com/spreadsheets/d/1ucFGWJT6NjXG0VFG2anscS8RPELydIrxr4Kxrax-dGs/edit?gid=60711146#gid=60711146";
  const chat_link = "https://chat.google.com/room/AAQAs-g2H4k?cls=7";
  const requestTemplateLink = "https://drive.google.com/drive/folders/1yA2zMKxqTzj6TMRc-qUd-3uPRCWech2N?usp=sharing";

  // --- Get email addresses and clean them ---
  const toEmails = (emailSheet.getRange("C1").getValue() || "").toString().trim();
  const ccEmails = (emailSheet.getRange("D1").getValue() || "").toString().trim();

  // --- Get required fields ---
  const description = lastNewProject.getRange("C1").getValue();
  const ticketId = lastNewProject.getRange("J1").getValue();
  const expectedTestingDate = lastNewProject.getRange("D1").getValue();
  const expectedLaunchDate = lastNewProject.getRange("F1").getValue();
  const projectDescription = lastNewProject.getRange("H1").getValue();

  // --- Get timestamp (confirm correct cell) ---
  const timestampCell = lastNewProject.getRange("A1").getValue(); // change cell if needed

  // Validate timestamp
  if (!timestampCell) {
    Logger.log("No timestamp found for new project, email not sent.");
    return;
  }

  const currentTimestamp = (timestampCell instanceof Date)
    ? Utilities.formatDate(timestampCell, Session.getScriptTimeZone(), "MM-dd-yyyy HH:mm:ss")
    : timestampCell.toString();

  // --- Use separate key for project email ---
  const scriptProps = PropertiesService.getScriptProperties();
  const lastTimestamp = scriptProps.getProperty("lastSentProjectTimestamp");

  // --- Send only if new ---
  if (currentTimestamp && currentTimestamp !== lastTimestamp) {
    // Validate required fields
    if (!ticketId || !description) {
      Logger.log("Missing required fields for new project email, not sent.");
      return;
    }

    const subject = `${ticketId} - M Tech New Project`;

    const body = `
      <p><strong>M Tech - New Project Request</strong></p>
      <p>Project ID: ${ticketId}<br>
         Project Feature: ${description}<br>
         Expected Testing Date: ${expectedTestingDate}<br>
         Expected Launch Date: ${expectedLaunchDate}<br>
         Project Description: ${projectDescription}</p>
      <p><a href="${requestTemplateLink}">Project Request Template Docs Drive</a></p>
      <p><a href="${new_project_link}">Click here to view the status</a></p>
      <p><a href="${chat_link}">You can chat with IT Team Here</a></p>
      <p>This email is generated by BI Team<br>
        Best Regard,<br>
      <strong>Marathon BI Team</strong></p>
    `;

    try {
      MailApp.sendEmail({
        to: toEmails,
        cc: ccEmails,
        subject: subject,
        htmlBody: body,
        name: 'Marathon BI'
      });
      Logger.log("New Project email sent: " + ticketId);

      // Save timestamp
      scriptProps.setProperty("lastSentProjectTimestamp", currentTimestamp);
    } catch (e) {
      Logger.log("Error sending project email: " + e.toString());
    }
  } else {
    Logger.log("No new project timestamp or timestamp already processed.");
  }
}


function onEdit(e) {
    Logger.log('Script has been triggered!'); // Check the logs to see this message
    
    const dropdownCol = 11;
    const timeCellCol = 19;
    const sheet = e.source.getActiveSheet();
    const range = e.range;
    const row = range.getRow();
    const col = range.getColumn();

//   const temp_time = Utilities.formatDate(new Date(), sheet.getSpreadsheetTimeZone(), 'HH:mm');

    // Get the current time and format it directly
    const now = new Date();
    let hours = now.getHours();
    const minutes = now.getMinutes().toString().padStart(2, '0');
    const seconds = now.getSeconds().toString().padStart(2, '0');

    const period = hours >= 12 ? 'PM' : 'AM';

    hours = hours % 12;
    hours = hours ? hours : 12; // if hour is 0 (midnight), change it to 12

    const formattedTime = `${hours}:${minutes}:${seconds} ${period}`;

    if (col === dropdownCol) {
        const status = e.value;
        const timeCell = sheet.getRange(row, timeCellCol);
        if (status === 'Closed' && timeCell.isBlank()) {
            timeCell.setValue(formattedTime);
        }
    }
}